#!/bin/sh
#
# Copyright (C) 2017 openwrt-ssr
# Copyright (C) 2017 yushi studio <ywb94@qq.com>
#
# This is free software, licensed under the GNU General Public License v3.
# See /LICENSE for more information.
#
NAME=shadowsocksr
LOCK_FILE="/var/lock/ssr-monitor.lock"
[ -f "$LOCK_FILE" ] && exit 2
touch "$LOCK_FILE"
server_process_count=$1
redir_tcp_process=$2
redir_udp_process=$3
local_process=$4
pdnsd_process=$5
if [ -z "$pdnsd_process" ]; then
	pdnsd_process=0
fi
i=0

while [ "1" == "1" ]; do #死循环
	sleep 000030s
	#redir tcp
	if [ "$redir_tcp_process" -gt 0 ]; then
		icount=$(busybox ps -w | grep ssr-retcp | grep -v grep | wc -l)
		if [ "$icount" == 0 ]; then
			logger -t "$NAME" "ssrplus redir tcp error.restart!"
			echolog "ssrplus redir tcp error.restart!"
			/usr/bin/shadowsocks.sh restart
			exit 0
		fi
	fi
	#redir udp
	if [ "$redir_udp_process" -gt 0 ]; then
		icount=$(busybox ps -w | grep ssr-reudp | grep -v grep | wc -l)
		if [ "$icount" == 0 ]; then
			logger -t "$NAME" "ssrplus redir udp error.restart!"
			echolog "ssrplus redir udp error.restart!"
			/usr/bin/shadowsocks.sh restart
			exit 0
		fi
	fi
	#server
	if [ "$server_process_count" -gt 0 ]; then
		icount=$(busybox ps -w | grep ssr-server | grep -v grep | wc -l)
		if [ "$icount" -lt "$server_process_count" ]; then #如果进程挂掉就重启它
			logger -t "$NAME" "ssrplus server error.restart!"
			echolog "ssrplus server error.restart!"
			kill -9 $(busybox ps -w | grep ssr-server | grep -v grep | awk '{print $1}') >/dev/null 2>&1
			/usr/bin/shadowsocks.sh restart
			exit 0
		fi
	fi
	#localsocks
	if [ "$local_process" -gt 0 ]; then
		icount=$(busybox ps -w | grep ssr-local | grep -v grep | wc -l)
		if [ "$icount" -lt "$local_process" ]; then #如果进程挂掉就重启它
			logger -t "$NAME" "global socks server error.restart!"
			echolog "global socks server error.restart!"
			kill -9 $(busybox ps -w | grep ssr-local | grep -v grep | awk '{print $1}') >/dev/null 2>&1
			/usr/bin/shadowsocks.sh restart
			exit 0
		fi
	fi
	#pdnsd
	if [ "$pdnsd_process" -gt 0 ]; then
		icount=$(busybox ps -w | grep $TMP_BIN_PATH/pdnsd | grep -v grep | wc -l)
		if [ "$icount" -lt "$pdnsd_process" ]; then #如果进程挂掉就重启它
			logger -t "$NAME" "pdnsd tunnel error.restart!"
			echolog "pdnsd tunnel error.restart!"
			if [ -f /var/run/pdnsd.pid ]; then
				kill $(cat /var/run/pdnsd.pid) >/dev/null 2>&1
			else
				kill -9 $(ps | grep $TMP_PATH/pdnsd.conf | grep -v grep | awk '{print $1}') >/dev/null 2>&1
			fi
			ln_start_bin $(first_type pdnsd) pdnsd -c $TMP_PATH/pdnsd.conf
		fi
	fi
done
